server:
  servlet:
    contextPath: /api/
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
---
spring:
  profiles:
    active: local
    include: loauth

---

spring:
  profiles:
    active: prod
    include: poauth
---

spring:
  profiles:
    active: dev
    include: doauth